#!/usr/bin/env python3

import argparse
import json
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


from manchester import (BITRATE_10BASET, samplerate_hz, recover_logic,
    crossing_position, recover_bit_grid, decode_bits,
    byte_labels_lsb as bits_to_bytes_lsb, capture_channels)
from plot_labels import plot_label


def main():
    parser = argparse.ArgumentParser(
        description="Convert DOS1102 NPZ captures to SVG"
    )

    parser.add_argument("npz", help="NPZ file generated by scope.py")
    parser.add_argument("--capture", type=int, default=3,
                        help="1-based acquisition number")
    parser.add_argument("--mode", choices=("full", "zoom", "overlay", "all"),
                        default="all",
                        help="View to generate")
    parser.add_argument("--threshold", type=float, default=300,
                        help="Activity and hysteresis threshold (±value)")
    parser.add_argument("--zoom-before-us", type=float, default=1.0)
    parser.add_argument("--zoom-after-us", type=float, default=6.0)
    parser.add_argument("--start-us", type=float,
                        help="Manual start time for zoom/overlay")
    parser.add_argument("--duration-us", type=float,
                        help="Manual duration for zoom/overlay")
    parser.add_argument("--byte-offset", type=int, default=0,
                        help="Byte from the start of the frame after SFD")
    parser.add_argument("--bytes", type=int, default=1,
                        help="Number of bytes in the overlay")
    parser.add_argument("--preamble-bytes", type=int, default=7,
                        help="Preamble bytes before SFD")
    parser.add_argument("--output-prefix", default="capture")

    args = parser.parse_args()

    z = np.load(args.npz, allow_pickle=True)
    index = args.capture - 1
    ch1, ch2 = capture_channels(z, index)
    fs = samplerate_hz(z, index)

    diff = ch1 - ch2
    quiet_len = min(4000, len(diff) // 2)
    baseline = np.median(diff[:quiet_len])
    d = diff - baseline

    t_us = np.arange(len(d)) / fs * 1e6
    sample_period_ns = 1e9 / fs

    active = np.abs(d) > args.threshold
    indices = np.flatnonzero(active)

    if not len(indices):
        raise SystemExit("No activity was detected with the selected threshold")

    start = int(indices[0])
    end = int(indices[-1])
    duration_us = (end - start + 1) / fs * 1e6

    logic = recover_logic(d, args.threshold)
    first_boundary, first_center, bit_samples = recover_bit_grid(d, start, fs)
    bit_us = bit_samples / fs * 1e6

    prefix = Path(args.output_prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)

    generated = []

    # ---------------------------------------------------------
    # Full capture
    # ---------------------------------------------------------
    if args.mode in ("full", "all"):
        full_svg = Path(str(prefix) + "_full.svg")
        full_png = Path(str(prefix) + "_full.png")

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.plot(t_us, d, linewidth=0.7)
        ax.axvline(t_us[start], linestyle="--", linewidth=1)
        ax.axvline(t_us[end], linestyle="--", linewidth=1)
        ax.axvspan(t_us[start], t_us[end], alpha=0.10)

        ax.set_title(plot_label("capture_svg.full_title", capture=args.capture))
        ax.set_xlabel(plot_label("capture_svg.time_axis"))
        ax.set_ylabel(plot_label("capture_svg.amplitude_axis"))
        ax.grid(True, alpha=0.25)
        ax.text(
            t_us[start] + 2,
            np.max(d) * 0.80,
            plot_label("capture_svg.activity", duration_us=duration_us, start=start, end=end)
        )

        fig.tight_layout()
        fig.savefig(full_svg, format="svg")
        fig.savefig(full_png, dpi=180, metadata={"Software": "flipper-in-the-middle"})
        plt.close(fig)
        generated.extend((full_svg, full_png))

    # ---------------------------------------------------------
    # Zoomed capture
    # ---------------------------------------------------------
    if args.mode in ("zoom", "all"):
        zoom_svg = Path(str(prefix) + "_zoom.svg")

        if args.start_us is not None:
            z0_us = args.start_us
            z1_us = (
                z0_us + args.duration_us
                if args.duration_us is not None
                else z0_us + args.zoom_after_us
            )
        else:
            z0_us = t_us[start] - args.zoom_before_us
            z1_us = t_us[start] + args.zoom_after_us

        mask = (t_us >= z0_us) & (t_us <= z1_us)

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.plot(
            t_us[mask],
            d[mask],
            marker=".",
            markersize=3,
            linewidth=0.6,
            alpha=0.8
        )

        ax.set_title(plot_label("capture_svg.zoom_title", capture=args.capture,
                                sample_period_ns=sample_period_ns))
        ax.set_xlabel(plot_label("capture_svg.time_axis"))
        ax.set_ylabel(plot_label("capture_svg.amplitude_axis"))
        ax.grid(True, alpha=0.25)

        fig.tight_layout()
        fig.savefig(zoom_svg, format="svg")
        plt.close(fig)
        generated.append(zoom_svg)

    # ---------------------------------------------------------
    # Overlay: real capture plus the Python interpretation.
    # ---------------------------------------------------------
    if args.mode in ("overlay", "all"):
        overlay_svg = Path(str(prefix) + "_overlay.svg")
        overlay_png = Path(str(prefix) + "_overlay.png")

        # Honor a manually selected window. Automatic mode skips seven preamble
        # bytes plus one SFD; byte-offset starts at the first Ethernet frame byte.
        if args.start_us is not None:
            o0_us = args.start_us
            if args.duration_us is None:
                o1_us = o0_us + args.bytes * 8 * bit_us
            else:
                o1_us = o0_us + args.duration_us

            first_bit = int(round(
                (o0_us - first_boundary / fs * 1e6) / bit_us
            ))
            bit_count = max(1, int(round((o1_us - o0_us) / bit_us)))
            window_boundary_us = (
                first_boundary / fs * 1e6 + first_bit * bit_us
            )
        else:
            skipped_bits = (args.preamble_bytes + 1) * 8 + args.byte_offset * 8
            first_bit = skipped_bits
            bit_count = args.bytes * 8
            window_boundary_us = (
                first_boundary / fs * 1e6 + first_bit * bit_us
            )
            o0_us = window_boundary_us - 0.10
            o1_us = (
                window_boundary_us
                + bit_count * bit_us
                + 0.10
            )

        mask = (t_us >= o0_us) & (t_us <= o1_us)

        if not np.any(mask):
            raise SystemExit("The overlay window falls outside the capture")

        decoded = decode_bits(
            logic,
            first_boundary + first_bit * bit_samples,
            bit_samples,
            bit_count
        )
        decoded_bytes = bits_to_bytes_lsb(decoded)

        peak = max(
            abs(float(np.min(d[mask]))),
            abs(float(np.max(d[mask]))),
            args.threshold * 2
        )
        overlay_amp = peak * 0.62
        logic_overlay = logic.astype(float) * overlay_amp

        fig, ax = plt.subplots(figsize=(16, 7))

        ax.plot(
            t_us[mask],
            d[mask],
            linewidth=0.65,
            alpha=0.50,
            label=plot_label("capture_svg.real_signal")
        )
        ax.scatter(
            t_us[mask],
            d[mask],
            s=17,
            label=plot_label("capture_svg.real_samples")
        )
        ax.step(
            t_us[mask],
            logic_overlay[mask],
            where="post",
            linewidth=2.0,
            label=plot_label("capture_svg.logical_level", threshold=args.threshold)
        )

        ax.axhline(args.threshold, linestyle="--", linewidth=0.7, alpha=0.4)
        ax.axhline(-args.threshold, linestyle="--", linewidth=0.7, alpha=0.4)
        ax.axhline(0, linewidth=0.5, alpha=0.3)

        label_y = peak * 1.28
        byte_y = peak * 1.48

        # Bit boundaries and Manchester centers.
        for n in range(bit_count + 1):
            x = window_boundary_us + n * bit_us
            strong = (n % 8 == 0)
            ax.axvline(
                x,
                linewidth=1.0 if strong else 0.45,
                alpha=0.55 if strong else 0.30
            )

        for n, bit in enumerate(decoded):
            mid = window_boundary_us + (n + 0.5) * bit_us
            ax.axvline(mid, linestyle=":", linewidth=0.5, alpha=0.4)
            ax.text(
                mid,
                label_y,
                "?" if bit is None else str(bit),
                ha="center",
                va="center",
                fontsize=11
            )

        # Per-byte labels.
        for bidx, value in enumerate(decoded_bytes):
            bx0 = window_boundary_us + bidx * 8 * bit_us
            bx1 = min(
                bx0 + 8 * bit_us,
                window_boundary_us + bit_count * bit_us
            )

            label = "??" if value is None else f"{value:02X}"
            logical_offset = args.byte_offset + bidx

            ax.text(
                (bx0 + bx1) / 2,
                byte_y,
                plot_label("capture_svg.byte", offset=logical_offset, value=label),
                ha="center",
                va="center",
                fontsize=10
            )

        bits_text = " ".join("?" if b is None else str(b) for b in decoded)

        ax.set_xlim(o0_us, o1_us)
        ax.set_ylim(-peak * 1.55, peak * 1.62)

        recovered_bits = plot_label("capture_svg.recovered_bits", bits=bits_text)
        ax.set_title(plot_label("capture_svg.overlay_title", capture=args.capture,
                                recovered_bits=recovered_bits))
        ax.set_xlabel(plot_label("capture_svg.time_axis"))
        ax.set_ylabel(plot_label("capture_svg.scaled_axis"))
        ax.grid(True, alpha=0.18)
        ax.legend(loc="lower left")

        ax.text(
            o0_us + (o1_us - o0_us) * 0.01,
            -peak * 1.42,
            plot_label("capture_svg.sampling_note", sample_rate_msps=fs / 1e6,
                       sample_period_ns=sample_period_ns, samples_per_bit=bit_samples),
            fontsize=9,
            ha="left"
        )

        fig.tight_layout()
        fig.savefig(overlay_svg, format="svg", bbox_inches="tight")
        fig.savefig(overlay_png, dpi=180, bbox_inches="tight",
                    metadata={"Software": "flipper-in-the-middle"})
        plt.close(fig)
        generated.extend((overlay_svg, overlay_png))

        print()
        print("=== OVERLAY ===")
        print("Bits :", bits_text)
        print(
            "Bytes:",
            " ".join("??" if b is None else f"{b:02X}" for b in decoded_bytes)
        )

    # ---------------------------------------------------------
    # Console summary
    # ---------------------------------------------------------
    print()
    print("Capture       :", args.capture)
    print("Sample rate   :", fs / 1e6, "MS/s")
    print("Sample period :", sample_period_ns, "ns")
    print("Samples/bit   :", bit_samples)
    print("Activity      :", start, "->", end)
    print("Duration      :", duration_us, "us")
    print("First center  :", first_center / fs * 1e6, "us")

    print()
    print("Generated:")
    for path in generated:
        print(" ", path)


if __name__ == "__main__":
    main()
